<?xml version="1.0" encoding="utf-8"?><Database Name="Trambambule" Class="TrambambuleDBContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.60.1.32;Initial Catalog=Trambambule;Persist Security Info=True;User ID=Trambambule_User" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TrambambuleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Match" Member="Matches">
    <Type Name="Match">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Match_TeamMatch" Member="TeamMatches" ThisKey="Id" OtherKey="MatchId" Type="TeamMatch" />
    </Type>
  </Table>
  <Table Name="dbo.TeamMatch" Member="TeamMatches">
    <Type Name="TeamMatch">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatchId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Goals" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Result" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="TeamMatch_TeamMatchPlayer" Member="TeamMatchPlayers" ThisKey="Id" OtherKey="TeamMatchId" Type="TeamMatchPlayer" />
      <Association Name="Match_TeamMatch" Member="Match" ThisKey="MatchId" OtherKey="Id" Type="Match" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Player" Member="Players">
    <Type Name="Player">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nickname" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Player_TeamMatchPlayer" Member="TeamMatchPlayers" ThisKey="Id" OtherKey="PlayerId" Type="TeamMatchPlayer" />
    </Type>
  </Table>
  <Table Name="dbo.TeamMatchPlayer" Member="TeamMatchPlayers">
    <Type Name="TeamMatchPlayer">
      <Column Name="TeamMatchId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Position" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Rating" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Player_TeamMatchPlayer" Member="Player" ThisKey="PlayerId" OtherKey="Id" Type="Player" IsForeignKey="true" />
      <Association Name="TeamMatch_TeamMatchPlayer" Member="TeamMatch" ThisKey="TeamMatchId" OtherKey="Id" Type="TeamMatch" IsForeignKey="true" />
    </Type>
  </Table>
</Database>